#!/bin/sh
/etc/init.d/tor start
/etc/init.d/privoxy start
echo " Please setup your browser to point to 127.0.0.1:8118"
echo " Use Ctrl-C to exit & shutdown tor/privoxy"
tail -f /var/log/tor.log
/etc/init.d/tor stop
/etc/init.d/privoxy stop
